/**
 * Machine-readable error codes returned in `{ success: false, code }` API responses.
 * The web app switches on these codes; never rename an existing code without updating clients.
 */
export const ERROR_CODES = {
  // Generic
  BAD_REQUEST: 'BAD_REQUEST',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  UNPROCESSABLE_ENTITY: 'UNPROCESSABLE_ENTITY',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Auth (used from Phase 4)
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  CSRF_INVALID: 'CSRF_INVALID',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',
  TOKEN_REUSED: 'TOKEN_REUSED',

  // Data layer
  DUPLICATE_KEY: 'DUPLICATE_KEY',
  INVALID_ID: 'INVALID_ID',

  // Shopping (Phase 6)
  OUT_OF_STOCK: 'OUT_OF_STOCK',
  INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
  PRODUCT_UNAVAILABLE: 'PRODUCT_UNAVAILABLE',
  CART_LIMIT_REACHED: 'CART_LIMIT_REACHED',
  WISHLIST_LIMIT_REACHED: 'WISHLIST_LIMIT_REACHED',
  ADDRESS_LIMIT_REACHED: 'ADDRESS_LIMIT_REACHED',

  // Checkout & payments (Phase 8)
  PRICE_CHANGED: 'PRICE_CHANGED',
  CART_NOT_READY: 'CART_NOT_READY',
  COUPON_INVALID: 'COUPON_INVALID',
  PAYMENT_VERIFICATION_FAILED: 'PAYMENT_VERIFICATION_FAILED',
  ORDER_NOT_PAYABLE: 'ORDER_NOT_PAYABLE',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  RETURN_NOT_ALLOWED: 'RETURN_NOT_ALLOWED',
  REVIEW_NOT_ALLOWED: 'REVIEW_NOT_ALLOWED',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
